"use client";

import { CSSProperties } from "react";
import type { Mockup } from "@/lib/types";

interface Props {
  mockup: Mockup;
  projectName: string;
}

export function MockupRenderer({ mockup, projectName }: Props) {
  switch (mockup.kind) {
    case "landing":
      return <LandingMockup projectName={projectName} variant={mockup.index} />;
    case "dashboard":
      return <DashboardMockup variant={mockup.index} />;
    case "pricing":
      return <PricingMockup variant={mockup.index} />;
    case "signup":
      return <SignupMockup projectName={projectName} variant={mockup.index} />;
    case "settings":
      return <SettingsMockup variant={mockup.index} />;
  }
}

const surface: CSSProperties = {
  background: "var(--ds-color-surface)",
  color: "var(--ds-color-text)",
  fontFamily: "var(--ds-font-family)",
  fontSize: "var(--ds-font-size-base)",
  lineHeight: "var(--ds-line-height)" as unknown as number,
  letterSpacing: "var(--ds-letter-spacing)",
};

const btnPrimary: CSSProperties = {
  background: "var(--ds-color-primary)",
  color: "white",
  padding: "var(--ds-space-3) var(--ds-space-5)",
  borderRadius: "var(--ds-radius-button)",
  fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
  boxShadow: "var(--ds-shadow)",
  display: "inline-flex",
  alignItems: "center",
  gap: "var(--ds-space-2)",
  cursor: "pointer",
};

const btnSecondary: CSSProperties = {
  background: "transparent",
  color: "var(--ds-color-text)",
  padding: "var(--ds-space-3) var(--ds-space-5)",
  borderRadius: "var(--ds-radius-button)",
  fontWeight: "var(--ds-font-weight-medium)" as unknown as number,
  border: "var(--ds-border-width) var(--ds-border-style) var(--ds-color-neutral)",
};

const card: CSSProperties = {
  background: "var(--ds-color-surface)",
  borderRadius: "var(--ds-radius-md)",
  boxShadow: "var(--ds-shadow-card)",
  border: "var(--ds-card-border)",
  padding: "var(--ds-space-5)",
};

function LandingMockup({
  projectName,
  variant,
}: {
  projectName: string;
  variant: number;
}) {
  const heroAlign = variant % 2 === 0 ? "center" : "left";
  return (
    <div style={{ ...surface, padding: "var(--ds-space-6)" }}>
      <header
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: "var(--ds-space-7)",
        }}
      >
        <div
          style={{
            fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
            fontSize: "var(--ds-font-size-lg)",
          }}
        >
          {projectName.slice(0, 18)}
        </div>
        <nav style={{ display: "flex", gap: "var(--ds-space-5)" }}>
          {["Product", "Pricing", "Docs", "Blog"].map((n) => (
            <span
              key={n}
              style={{
                color: "var(--ds-color-text-muted)",
                fontSize: "var(--ds-font-size-sm)",
              }}
            >
              {n}
            </span>
          ))}
          <button style={btnPrimary}>Get started</button>
        </nav>
      </header>

      <section
        style={{
          textAlign: heroAlign as "left" | "center",
          padding: "var(--ds-space-7) 0",
        }}
      >
        <div
          style={{
            display: "inline-block",
            padding: "var(--ds-space-1) var(--ds-space-3)",
            borderRadius: "999px",
            background: "var(--ds-color-primary)",
            color: "white",
            fontSize: "var(--ds-font-size-sm)",
            opacity: 0.95,
          }}
        >
          NEW · v1.0 OUT NOW
        </div>
        <h1
          style={{
            fontSize: "var(--ds-font-size-3xl)",
            fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
            margin: "var(--ds-space-4) 0 var(--ds-space-3)",
            lineHeight: 1.1,
          }}
        >
          Design Systems, <br />
          generated by AI.
        </h1>
        <p
          style={{
            color: "var(--ds-color-text-muted)",
            fontSize: "var(--ds-font-size-lg)",
            maxWidth: "560px",
            margin: heroAlign === "center" ? "0 auto" : "0",
          }}
        >
          DS 3종 + 시안 15종을 3분 안에. Token 수정은 모든 시안에 실시간 반영된다.
        </p>
        <div
          style={{
            marginTop: "var(--ds-space-5)",
            display: "flex",
            gap: "var(--ds-space-3)",
            justifyContent: heroAlign === "center" ? "center" : "flex-start",
          }}
        >
          <button style={btnPrimary}>Start free →</button>
          <button style={btnSecondary}>Watch demo</button>
        </div>
      </section>

      <section
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "var(--ds-space-4)",
          marginTop: "var(--ds-space-6)",
        }}
      >
        {[
          { t: "Tokens", d: "W3C DTCG 표준 JSON 으로 즉시 Export" },
          { t: "Realtime", d: "500ms 이내 모든 시안에 반영" },
          { t: "MCP", d: "Cursor·Claude Code 에서 직접 참조" },
        ].map((f) => (
          <div key={f.t} style={card}>
            <div
              style={{
                width: "32px",
                height: "32px",
                borderRadius: "var(--ds-radius-sm)",
                background: "var(--ds-color-primary)",
                marginBottom: "var(--ds-space-3)",
              }}
            />
            <div
              style={{
                fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
                fontSize: "var(--ds-font-size-lg)",
                marginBottom: "var(--ds-space-2)",
              }}
            >
              {f.t}
            </div>
            <div
              style={{
                color: "var(--ds-color-text-muted)",
                fontSize: "var(--ds-font-size-sm)",
              }}
            >
              {f.d}
            </div>
          </div>
        ))}
      </section>
    </div>
  );
}

function DashboardMockup({ variant }: { variant: number }) {
  return (
    <div
      style={{
        ...surface,
        background: "var(--ds-color-bg)",
        padding: "var(--ds-space-5)",
      }}
    >
      <header
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: "var(--ds-space-5)",
        }}
      >
        <div>
          <div
            style={{
              fontSize: "var(--ds-font-size-2xl)",
              fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
            }}
          >
            Overview
          </div>
          <div
            style={{
              fontSize: "var(--ds-font-size-sm)",
              color: "var(--ds-color-text-muted)",
              marginTop: "var(--ds-space-1)",
            }}
          >
            Last updated 2 minutes ago
          </div>
        </div>
        <button style={btnPrimary}>+ New report</button>
      </header>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: "var(--ds-space-4)",
        }}
      >
        {[
          { l: "Active Users", v: "12,438", d: "+8.2%" },
          { l: "Revenue", v: "$94,210", d: "+12.4%" },
          { l: "Conversion", v: "3.42%", d: "-0.4%" },
          { l: "Retention", v: "78.1%", d: "+1.1%" },
        ].map((m, i) => (
          <div key={m.l} style={card}>
            <div
              style={{
                fontSize: "var(--ds-font-size-sm)",
                color: "var(--ds-color-text-muted)",
              }}
            >
              {m.l}
            </div>
            <div
              style={{
                fontSize: "var(--ds-font-size-2xl)",
                fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
                marginTop: "var(--ds-space-2)",
              }}
            >
              {m.v}
            </div>
            <div
              style={{
                marginTop: "var(--ds-space-2)",
                fontSize: "var(--ds-font-size-sm)",
                color:
                  i === 2
                    ? "var(--ds-color-error)"
                    : "var(--ds-color-success)",
              }}
            >
              {m.d}
            </div>
          </div>
        ))}
      </div>

      <div
        style={{
          marginTop: "var(--ds-space-5)",
          display: "grid",
          gridTemplateColumns: variant % 2 === 0 ? "2fr 1fr" : "1fr 1fr",
          gap: "var(--ds-space-4)",
        }}
      >
        <div style={card}>
          <div
            style={{
              fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
              marginBottom: "var(--ds-space-4)",
            }}
          >
            Revenue trend
          </div>
          <svg viewBox="0 0 400 120" style={{ width: "100%", height: "120px" }}>
            <polyline
              fill="none"
              stroke="var(--ds-color-primary)"
              strokeWidth="2.5"
              points="0,90 40,72 80,80 120,55 160,62 200,42 240,50 280,30 320,38 360,22 400,28"
            />
            <polyline
              fill="none"
              stroke="var(--ds-color-secondary)"
              strokeWidth="1.5"
              strokeDasharray="3 3"
              points="0,100 40,95 80,90 120,85 160,80 200,75 240,70 280,65 320,60 360,55 400,50"
            />
          </svg>
        </div>
        <div style={card}>
          <div
            style={{
              fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
              marginBottom: "var(--ds-space-4)",
            }}
          >
            Top sources
          </div>
          {[
            { l: "Organic", v: 58 },
            { l: "Direct", v: 22 },
            { l: "Referral", v: 12 },
            { l: "Social", v: 8 },
          ].map((row) => (
            <div key={row.l} style={{ marginBottom: "var(--ds-space-3)" }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  fontSize: "var(--ds-font-size-sm)",
                  marginBottom: "var(--ds-space-1)",
                }}
              >
                <span>{row.l}</span>
                <span
                  style={{ color: "var(--ds-color-text-muted)" }}
                >{`${row.v}%`}</span>
              </div>
              <div
                style={{
                  height: "6px",
                  background: "var(--ds-color-neutral)",
                  opacity: 0.2,
                  borderRadius: "var(--ds-radius-sm)",
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    width: `${row.v}%`,
                    height: "100%",
                    background: "var(--ds-color-primary)",
                    opacity: 1,
                  }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function PricingMockup({ variant }: { variant: number }) {
  const tiers = [
    { name: "Free", price: 0, features: ["월 3회 생성", "PNG Export"] },
    {
      name: "Pro",
      price: 19,
      features: ["월 30회 생성", "전체 Export", "MCP 연동", "API Key"],
      highlight: true,
    },
    { name: "Team", price: 49, features: ["무제한 생성", "팀 공유", "우선 처리"] },
  ];
  return (
    <div style={{ ...surface, padding: "var(--ds-space-7)" }}>
      <div style={{ textAlign: "center", marginBottom: "var(--ds-space-7)" }}>
        <div
          style={{
            fontSize: "var(--ds-font-size-3xl)",
            fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
          }}
        >
          Simple, transparent pricing
        </div>
        <div
          style={{
            color: "var(--ds-color-text-muted)",
            fontSize: "var(--ds-font-size-lg)",
            marginTop: "var(--ds-space-3)",
          }}
        >
          No credit card required to start.
        </div>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "var(--ds-space-4)",
        }}
      >
        {tiers.map((t, i) => (
          <div
            key={t.name}
            style={{
              ...card,
              border: t.highlight
                ? `2px solid var(--ds-color-primary)`
                : "var(--ds-card-border)",
              transform:
                t.highlight && variant % 2 === 0 ? "translateY(-8px)" : "none",
            }}
          >
            {t.highlight && (
              <div
                style={{
                  display: "inline-block",
                  padding: "var(--ds-space-1) var(--ds-space-3)",
                  borderRadius: "999px",
                  background: "var(--ds-color-primary)",
                  color: "white",
                  fontSize: "var(--ds-font-size-sm)",
                  marginBottom: "var(--ds-space-3)",
                }}
              >
                Recommended
              </div>
            )}
            <div
              style={{
                fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
                fontSize: "var(--ds-font-size-lg)",
              }}
            >
              {t.name}
            </div>
            <div
              style={{
                fontSize: "var(--ds-font-size-3xl)",
                fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
                margin: "var(--ds-space-3) 0 var(--ds-space-4)",
              }}
            >
              ${t.price}
              <span
                style={{
                  fontSize: "var(--ds-font-size-base)",
                  fontWeight: "var(--ds-font-weight-regular)" as unknown as number,
                  color: "var(--ds-color-text-muted)",
                }}
              >
                /mo
              </span>
            </div>
            <button
              style={{
                ...(t.highlight ? btnPrimary : btnSecondary),
                width: "100%",
                justifyContent: "center",
              }}
            >
              Choose {t.name}
            </button>
            <ul
              style={{
                marginTop: "var(--ds-space-5)",
                fontSize: "var(--ds-font-size-sm)",
                color: "var(--ds-color-text-muted)",
                listStyle: "none",
                padding: 0,
              }}
            >
              {t.features.map((f) => (
                <li
                  key={f}
                  style={{
                    padding: "var(--ds-space-2) 0",
                    borderTop: `1px solid var(--ds-color-neutral)22`,
                  }}
                >
                  ✓ {f}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}

function SignupMockup({
  projectName,
  variant,
}: {
  projectName: string;
  variant: number;
}) {
  return (
    <div
      style={{
        ...surface,
        background: "var(--ds-color-bg)",
        padding: "var(--ds-space-7)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "100%",
      }}
    >
      <div
        style={{
          ...card,
          width: variant % 2 === 0 ? "440px" : "520px",
          maxWidth: "100%",
        }}
      >
        <div
          style={{
            fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
            fontSize: "var(--ds-font-size-2xl)",
          }}
        >
          {projectName.slice(0, 22)} 시작하기
        </div>
        <div
          style={{
            color: "var(--ds-color-text-muted)",
            fontSize: "var(--ds-font-size-sm)",
            marginTop: "var(--ds-space-2)",
          }}
        >
          신용카드 없이 30초만에 가입.
        </div>

        <div
          style={{
            marginTop: "var(--ds-space-5)",
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: "var(--ds-space-3)",
          }}
        >
          {["Google", "GitHub"].map((p) => (
            <button
              key={p}
              style={{
                ...btnSecondary,
                width: "100%",
                justifyContent: "center",
              }}
            >
              Continue with {p}
            </button>
          ))}
        </div>

        <div
          style={{
            textAlign: "center",
            color: "var(--ds-color-text-muted)",
            fontSize: "var(--ds-font-size-sm)",
            margin: "var(--ds-space-5) 0",
          }}
        >
          or
        </div>

        {["Work email", "Password"].map((l) => (
          <div key={l} style={{ marginBottom: "var(--ds-space-3)" }}>
            <div
              style={{
                fontSize: "var(--ds-font-size-sm)",
                fontWeight: "var(--ds-font-weight-medium)" as unknown as number,
                marginBottom: "var(--ds-space-2)",
              }}
            >
              {l}
            </div>
            <div
              style={{
                background: "var(--ds-input-bg)",
                borderRadius: "var(--ds-radius-sm)",
                border:
                  "var(--ds-border-width) var(--ds-border-style) var(--ds-color-neutral)",
                padding: "var(--ds-space-3) var(--ds-space-4)",
                color: "var(--ds-color-text-muted)",
                fontSize: "var(--ds-font-size-base)",
              }}
            >
              {l === "Work email" ? "you@company.com" : "••••••••"}
            </div>
          </div>
        ))}

        <button
          style={{
            ...btnPrimary,
            width: "100%",
            justifyContent: "center",
            marginTop: "var(--ds-space-5)",
          }}
        >
          Create account
        </button>
      </div>
    </div>
  );
}

function SettingsMockup({ variant }: { variant: number }) {
  return (
    <div style={{ ...surface, padding: "var(--ds-space-6)" }}>
      <div
        style={{
          fontSize: "var(--ds-font-size-2xl)",
          fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
          marginBottom: "var(--ds-space-5)",
        }}
      >
        Account settings
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: variant % 2 === 0 ? "200px 1fr" : "240px 1fr",
          gap: "var(--ds-space-5)",
        }}
      >
        <nav>
          {["Profile", "Notifications", "Billing", "API Keys", "Security"].map(
            (n, i) => (
              <div
                key={n}
                style={{
                  padding: "var(--ds-space-3) var(--ds-space-4)",
                  borderRadius: "var(--ds-radius-sm)",
                  background:
                    i === 0 ? "var(--ds-color-primary)" : "transparent",
                  color: i === 0 ? "white" : "var(--ds-color-text)",
                  fontSize: "var(--ds-font-size-sm)",
                  fontWeight:
                    i === 0
                      ? ("var(--ds-font-weight-bold)" as unknown as number)
                      : ("var(--ds-font-weight-medium)" as unknown as number),
                  marginBottom: "var(--ds-space-1)",
                }}
              >
                {n}
              </div>
            ),
          )}
        </nav>

        <div style={card}>
          <div
            style={{
              fontWeight: "var(--ds-font-weight-bold)" as unknown as number,
              fontSize: "var(--ds-font-size-lg)",
            }}
          >
            Profile
          </div>
          <div
            style={{
              color: "var(--ds-color-text-muted)",
              fontSize: "var(--ds-font-size-sm)",
              marginTop: "var(--ds-space-2)",
              marginBottom: "var(--ds-space-5)",
            }}
          >
            팀원에게 노출되는 정보이다.
          </div>

          {[
            { l: "Name", v: "안승준" },
            { l: "Email", v: "demo@designgenerator.io" },
            { l: "Role", v: "Designer · Pro" },
          ].map((f) => (
            <div
              key={f.l}
              style={{
                display: "grid",
                gridTemplateColumns: "120px 1fr",
                padding: "var(--ds-space-3) 0",
                borderTop: `1px solid var(--ds-color-neutral)22`,
                fontSize: "var(--ds-font-size-sm)",
              }}
            >
              <div style={{ color: "var(--ds-color-text-muted)" }}>{f.l}</div>
              <div
                style={{
                  fontWeight:
                    "var(--ds-font-weight-medium)" as unknown as number,
                }}
              >
                {f.v}
              </div>
            </div>
          ))}

          <div
            style={{
              marginTop: "var(--ds-space-5)",
              display: "flex",
              gap: "var(--ds-space-3)",
            }}
          >
            <button style={btnPrimary}>Save changes</button>
            <button style={btnSecondary}>Cancel</button>
          </div>
        </div>
      </div>
    </div>
  );
}
